### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by L1ghtman2k** [laundmo/northstar-parseable-logs#1]
Our tool pulls the latest stable GitHub releases, and we were wondering if it would be possible to have such releases for this repo?

You can automate mod ZIP generation with actions like: https://github.com/Dinorush/LTSRebalance/blob/main/.github/workflows/build_zip.yml

**Comment by laundmo** [comment]
i will not be releasing on GitHub, please use the https://northstar.thunderstore.io API for updates, as that is what all mods and mod managers should use long-term
